export const CART_DATA = {
  INITSTATE: 'CART_DATA_INITSTATE',
  INIT: 'CART_DATA_INIT',
  START: 'CART_DATA_START',
  REJECTED: 'CART_DATA_REJECTED',
  FULFILLED: 'CART_DATA_FULFILLED',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART'
};

export const PRODUCT_DATA = {
  INITSTATE: 'PRODUCT_DATA_INITSTATE',
  INIT: 'PRODUCT_DATA_INIT',
  START: 'PRODUCT_DATA_START',
  REJECTED: 'PRODUCT_DATA_REJECTED',
  FULFILLED: 'PRODUCT_DATA_FULFILLED',
  FETCH_DETAIL_START: 'PRODUCT_DATA_FETCH_DETAIL_START',
  FETCH_DETAIL_FULFILLED: 'PRODUCT_DATA_FETCH_DETAIL_FULFILLED',
  FETCH_DETAIL_REJECTED: 'PRODUCT_DATA_FETCH_DETAIL_REJECTED',
  FETCH_SEARCH_START: 'PRODUCT_DATA_FETCH_SEARCH_START',
  FETCH_SEARCH_FULFILLED: 'PRODUCT_DATA_FETCH_SEARCH_FULFILLED',
  FETCH_SEARCH_REJECTED: 'PRODUCT_DATA_FETCH_SEARCH_REJECTED'
};

export const USER_DATA = {
  INITSTATE: 'USER_DATA_INITSTATE',
  INIT: 'USER_DATA_INIT',
  START: 'USER_DATA_START',
  REJECTED: 'USER_DATA_REJECTED',
  FULFILLED: 'USER_DATA_FULFILLED',
  LOGIN_START: 'USER_DATA_LOGIN_START',
  LOGIN_FULFILLED: 'USER_DATA_LOGIN_FULFILLED',
  LOGIN_REJECTED: 'USER_DATA_LOGIN_REJECTED',
  REGISTER_START: 'USER_DATA_REGISTER_START',
  REGISTER_FULFILLED: 'USER_DATA_REGISTER_FULFILLED',
  REGISTER_REJECTED: 'USER_DATA_REGISTER_REJECTED',
  LOGOUT_START: 'USER_DATA_LOGOUT_START',
  LOGOUT_FULFILLED: 'USER_DATA_LOGOUT_FULFILLED',
  LOGOUT_REJECTED: 'USER_DATA_LOGOUT_REJECTED',
  CLEAR_ERROR: 'USER_DATA_CLEAR_ERROR'
};

export const DEPARTMENT_DATA = {
  INITSTATE: 'DEPARTMENT_DATA_INITSTATE',
  START: 'DEPARTMENT_DATA_START',
  REJECTED: 'DEPARTMENT_DATA_REJECTED',
  FULFILLED: 'DEPARTMENT_DATA_FULFILLED'
};

export const ORDER_DATA = {
  INITSTATE: 'ORDER_DATA_INITSTATE',
  ADD_ORDER: 'ADD_ORDER',
  GET_ORDERS: 'GET_ORDERS',
  GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
  CLEAR_ORDERS: 'CLEAR_ORDERS'
};

export const CATEGORY_DATA = {
  FETCH_CATEGORIES_START: 'CATEGORY_DATA_FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_FULFILLED: 'CATEGORY_DATA_FETCH_CATEGORIES_FULFILLED',
  FETCH_CATEGORIES_REJECTED: 'CATEGORY_DATA_FETCH_CATEGORIES_REJECTED',
  FETCH_CATEGORY_PRODUCTS_START: 'CATEGORY_DATA_FETCH_CATEGORY_PRODUCTS_START',
  FETCH_CATEGORY_PRODUCTS_FULFILLED: 'CATEGORY_DATA_FETCH_CATEGORY_PRODUCTS_FULFILLED',
  FETCH_CATEGORY_PRODUCTS_REJECTED: 'CATEGORY_DATA_FETCH_CATEGORY_PRODUCTS_REJECTED'
};